### ISSUE TITLE
right click menu does not indicate whether a new setting is applied on Deepin 15.9

### ISSUE THREAD

**Issue by guanghwang** [ypingcn/BingWallpaper#10]
Please see the linked screen recorder.

https://drive.google.com/file/d/1XWmrMCz5AolESguJYtQXWGhyW_OyMf0G/view?usp=sharing

Here is configuration found in `ypingcn` folder.
```
[General]
lang=en-US
```

**Comment by ypingcn** [comment]
if you mean language switch setting , this is a known issue , I am trying my best to solve the issue.

It looks like your wallpaper has beed updated to the lastest Bingwallpaper

any other problem , please give more specification , thanks

**Comment by guanghwang** [comment]
I expect there is an indicator (such as a check mark or a checkbox) when I click `Auto Setting` or  `Specific DE - Deepin`. such as
![example](https://user-images.githubusercontent.com/12839553/51394880-6edacf00-1b09-11e9-8052-8fbccdcd015f.png)
) 

 I also expect that the configuration file would change when I check these options.

Thank you for this nice program.

**Comment by ypingcn** [comment]
@guanghwang  no , auto setting means the program will detect your desktop environment to decide how to update your wallpaper , I will consider to use other word to express "auto" in updating wallpaper.

thank you for your appreciation

**Comment by guanghwang** [comment]
Got it. Thanks
